### ISSUE TITLE
Link in Games broken

### ISSUE THREAD

**Issue by qst0** [aureliojargas/sed.sf.net#6]
http://jcsu.jesus.cam.ac.uk/~gsb29/sedgames.html

Pong 1 player and 2 player link to this site and this link is broken

**Comment by aureliojargas** [comment]
Thanks for the report!

Unfortunately, I cannot find it in the Internet Archive (https://web.archive.org/web/20080303152220/http://jcsu.jesus.cam.ac.uk/~gsb29/sedgames.html), and neither by a Google search :(

Since there's the working local copy of those scripts (the `[colored]` link next to the broken link), I think I'll just leave it as it is, so we keep a reference to the URL that one day served those scripts.
